name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Install dependencies
      run: |
        python3 -m venv ./venv
        source venv/bin/active
        pip install -r requirements.txt

